export const ALL_CAROUSEL_REQUEST = "ALL_CAROUSEL_REQUEST";
export const ALL_CAROUSEL_SUCCESS = "ALL_CAROUSEL_SUCCESS";
export const ALL_CAROUSEL_FAIL = "ALL_CAROUSEL_FAIL";


export const NEW_CAROUSEL_REQUEST = "NEW_CAROUSEL_REQUEST";
export const NEW_CAROUSEL_SUCCESS = "NEW_CAROUSEL_SUCCESS";
export const NEW_CAROUSEL_RESET = "NEW_CAROUSEL_RESET";
export const NEW_CAROUSEL_FAIL = "NEW_CAROUSEL_FAIL:"

export const UPDATE_CAROUSEL_REQUEST = "UPDATE_CAROUSEL_REQUEST";
export const UPDATE_CAROUSEL_SUCCESS = "UPDATE_CAROUSEL_SUCCESS";
export const UPDATE_CAROUSEL_RESET = "UPDATE_CAROUSEL_RESET";
export const UPDATE_CAROUSEL_FAIL = "UPDATE_CAROUSEL_FAIL";

export const DELETE_CAROUSEL_REQUEST = "DELETE_CAROUSEL_REQUEST";
export const DELETE_CAROUSEL_SUCCESS = "DELETE_CAROUSEL_SUCCESS";
export const DELETE_CAROUSEL_RESET = "DELETE_CAROUSEL_RESET";
export const DELETE_CAROUSEL_FAIL = "DELETE_CAROUSEL_FAIL";

export const CAROUSEL_DETAILS_REQUEST = "CAROUSEL_DETAILS_REQUEST";
export const CAROUSEL_DETAILS_SUCCESS = "CAROUSEL_DETAILS_SUCCESS";
export const CAROUSEL_DETAILS_FAIL = "CAROUSEL_DETAILS_FAIL";


export const CLEAR_CAROUSEL_ERRORS = "CLEAR_CAROUSEL_ERRORS";